version: "3.8"
services:
  web:
    image: marqueschristmann8080/frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend
    command: sh -c "git pull origin master && npm install && npm start"

  api:
    image: marqueschristmann8080/backend
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks: 
     - network-backend
    command: sh -c "git pull origin master && npm install && npm start"
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    # uncomment following lines to access db locally
    # ports:
    #   - 27017:27017
    networks: 
     - network-backend

networks:
  network-backend:
    driver: bridge

volumes: 
  mongodb_data:
